[package]
name = "eots"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
hex         = { workspace = true }
k256        = { workspace = true }
sha2        = { workspace = true }
thiserror   = { workspace = true }

[dev-dependencies]
rand        = { workspace = true }
test-utils  = { path = "../../packages/test-utils" }
