[package]
name = "babylon-apis"
version.workspace = true
edition.workspace = true

[dependencies]
babylon-bitcoin  = { path = "../bitcoin" }
babylon-merkle   = { path = "../merkle" }
bech32           = { workspace = true }
cosmwasm-std     = { workspace = true }
cosmwasm-schema  = { workspace = true }
hex              = { workspace = true }
tendermint-proto = { workspace = true }
thiserror        = { workspace = true }
babylon-proto    = { workspace = true }