[package]
name = "babylon-bindings-test"
version = "0.4.0"
authors = ["Babylon Labs <admin@babylonlabs.io>"]
edition = "2021"
description = "Multitest (and other test helpers) support for Babylon-specific contracts"
repository = "https://github.com/babylonlabs-io/babylon-contract"
homepage = "https://babylonlabs.io"
license = "Apache-2.0"

[dependencies]
anyhow           = { workspace = true }
babylon-bindings = { version = "0.4.0", path = "../bindings" }
cosmwasm-std     = { workspace = true }
cw-multi-test    = { workspace = true }
cw-storage-plus  = { workspace = true }
thiserror        = { workspace = true }
schemars         = { workspace = true }
serde            = { workspace = true }
