[alias]
unit-test = "test --lib"
integration = "run-script integration"
gen-data = "run-script gen-data"
gen-proto = "run-script gen-proto"
gen-schema = "run-script gen-schema"
build-optimizer = "run-script build-optimizer"
optimize = "run-script optimize"
precommit = "run-script precommit"
lint = "run-script lint"
fix-lint = "run-script fix-lint"