name: babylonchain/babylon-contract/local-tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  local-build-test:
    runs-on: ubuntu-latest
    container:
      image: rust:1.78.0
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Build contracts, check formats, and run unit tests
      run: cargo test --lib
